services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./wordpress-scrape:/usr/share/nginx/html
    command: >
      /bin/sh -c "
        echo 'Server running at http://localhost:8080'
        /usr/sbin/nginx -g \"daemon off;\"
      "
